[package]
name = "freecli"
version = "0.2.0"
edition = "2024"

[dependencies]
console = "0.15.11"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
clap = { version = "4.5", features = ["derive"] }
dirs = "6.0.0"
